### PR TITLE
Auto Updater, Color Themes, Type Fixes, Improved Filter UI

### PR DESCRIPTION
**Pull request by InsulatorGMan**
Added the ability for the app to fetch and download updates from a Hazel server deployed on a free tier [Vercel Server](https://pd3-challenge-viewer-vercel-update-server-a18tj6086.vercel.app). There were merge conflicts in the old pr.

### CODE REVIEW

**Comment by InsulatorGMan** [comment]
Added an ability to switch color themes (light, dark) based on system preferences.
[video](https://youtu.be/bDOHfEpZls4)

**Comment by InsulatorGMan** [comment]
Also I fixed some type errors.

**Comment by InsulatorGMan** [comment]
Video showing off new UI [here](https://youtu.be/O8COG-gGtsY).

**Comment by Ldalvik** [comment]
I personally forked this project to make it fit my screen better, but your changes clean up the dropdowns that were getting lost on my monitor! So I'll probably just use this branch for now.

Only thing I think could be changed is the button to access the options, people can be tone-deaf to unlabeled stuff like that (im one of them). Otherwise I hope they merge some of these features!

**Comment by InsulatorGMan** [comment]
Thanks for the feedback, if you have any suggestions on how I can improve it please let me know.

**Comment by InsulatorGMan** [comment]
@theoarav I don't know if you have seen this or not, but I think it would be good to merge this branch for a later release.

**Comment by InsulatorGMan** [comment]
I think I improved the readability of the filters: image

**Comment by Nothing4You** [comment]
when switching around filters a lot, e.g. to pin certain challenges that you're currently going for, having the filters in an extra menu depth is not that user friendly.

**Comment by InsulatorGMan** [comment]
Do you have a suggestion for how I could improve it?

**Comment by Nothing4You** [comment]
maybe allowing the filter view to be toggled without being a layer on top?

**Comment by theoarav** [comment]
Great improvements ! Haven't seen it before will surely accept your PR asap !
Sorry for answering so late

**Comment by DudiVok** [comment]
@InsulatorGMan I've taken a look at your commits and I have a few things I noticed before merging.
- The loading screen is fine and dandy, until you refetch the data. It shows up in the background without actually hiding the cards.
- It may be me, but I can't seem to find the status selections in the filters tab. By statuses I mean the completed, in-progress and locked checkboxes which was previously there.

If you want we can discuss about these on discord (#dudivok or #elmoren)

**Comment by ActiveLurker** [comment]
Firstly I'd like to say thank you for making up for the shortfalls of the dev. Secondly, I joined specifically to comment here, so apologies if this is not the correct place. 

May I suggest a few filter options with a view of making the app easier to navigate from a user perspective? 
As I'm currently looking for challenges that are nearing completion, navigating through more than 1000 challenges across various trees makes pining ones of interest a slight pain. 
Adding a custom filter to only show challenges that are >%25 >%50 >75% complete would be a life saver allowing users to focus on where to apply their attention in game and maximize their XPs gain per hour.

I also noticed a mouse scrolling issue, whereby the cards would be caught in a scroll loop repeatedly going up & down, which made my CPU fan spin up like crazy. This occurred on Brave browser @ 2560x1440 res on windows 10. Feel free to ask for more info if it's required.

Again if this comment/suggestion is inappropriate or in the wrong place, then my sincere apologies, my intention is to make what you have created, even better.

Thank you.

**Comment by DudiVok** [comment]
@ActiveLurker We'll you could have made it in the issues tab instead, but theres no problem with you commenting here.

The filtering option is a good idea, I'll make a filter for it soon and will probably make a new release later today. I just need to think about how to implement it, since creating separate filters for each percentage feels a bit off. Maybe i'll also add a sort by select(currently the challenges are sorted on their names A-Z) that will sort the challenges based on their completion percentages and if you filter out the completed challenges you would see the challenges that you are the nearest towards completion first, but i'll try to create that percentage filter too.

About the CPU ramping up issue tho. How did you start the app using brave? As far as I know the framework thats used for creating the app, electron, is based on chromium which is the engine of both chrome and brave, but its not actually running in either of those browsers. I haven't actually looked at the cpu usage before since I had no troubles like that, but for me, running W11 on 1440p the cpu usage caps at around 20% when scrolling very fast (on a i7-9750H mobile processor), and I havent had issues with scrolling either. Could you describe how you actually use the app and how do you manage to get into said issue?

**Comment by theoarav** [comment]
I merged your PR, fixed the 2 issues mentionned by @DudiVok too.
I'll remove the Vercel auto updater to make it with github directly so it stays fully open source.

**Comment by ActiveLurker** [comment]
Brave actually had nothing to do with it, other than being open when I run the app (so I assumed it was a possible confliction although unlikely, I know nothing about scripting or languages, I'm a complete noob). 

I've had it open ever I since I sent my previous comment, and it hasn't done it again, so I would assume it was just at load while pulling all the challenge info from the server and me trying to scroll too fast with my free wheel mouse. 
Seems I needed to let the app gather all my account challenge completion first before racing through it. But like I said, I'm a noob and don't know much about this sort of thing.

Really appreciate you looking into adding the extra filters.

discord: milo6942

**Comment by InsulatorGMan** [comment]
I would like you to consider adding the "Theme switch". But maybe it would be better with an override.

**Pull request merged**
